server:
  port: 5889
#向注册中心注册的名字
spring:
  application:
    name: common-zuul
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
#设置注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
zuul:
  routes:
    student-client:
      path: /students/**
    user-client:
      path: /user/**
    host:
      connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
      socket-timeout-millis: 60000   #socket超时
  prefix: /usian

