server:
  port:
   8888
  # 不注册进注册中心
  # eureka.client.register-with-eureka=false
  # 不需要拉去服务
  # eureka.client.fetch-registry=false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
spring:
  rabbitmq:
     port: 5672
     host: localhost
     username: admin
     password: 123
     virtual-host: /usian
