eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 6688
spring:
  application:
    name: student-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/p8_student?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 960907
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
# 开启feign 对hystrix的使用
feign:
  hystrix:
    enabled: true
ribbon:
    # 指的是建立连接后从服务器读取到可用资源所用的时间
   ConnectTimeout: 5000
    # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所有时间
   ReadTimeout: 5000



#hystrix:
#  command:
#    default:
#      circuitBreaker:
#        #断容器最小请求数，达到这个值过后才开始计算是否打开熔断器
#        requestVolumeThreshold=3
#        #错误百分比条件，达到熔断器最小请求数后错误率达到百分之多少后打开熔断器
#        errorThresholdPercentage=5
#        #默认5秒; 熔断器打开后多少秒后 熔断状态变成半熔断状态(对该微服务进行一次请求尝试，不成功则状态改成熔断，成功则关闭熔断器
#        sleepWindowInMilliseconds=5000
